### ISSUE TITLE
Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by kenahrens** [kenahrens/nr-synthetics-plugin#4]
Issue reported by @eshwarg

Thu, 20 Apr 2017 09:28:24 GMT - info: * Frequency is every 30s, cron: (*/30 * * * * *)
Thu, 20 Apr 2017 09:28:24 GMT - info: * Running as a single config.
Thu, 20 Apr 2017 09:28:30 GMT - info: Starting poll cycle with NODE_ENV Environment: default
Thu, 20 Apr 2017 09:28:30 GMT - info: getMonitorList for config: newrelic
Thu, 20 Apr 2017 09:28:31 GMT - error: Error on Insights monitor list call
Thu, 20 Apr 2017 09:28:31 GMT - error: Error: self signed certificate in certificate chain
at TLSSocket. (_tls_wrap.js:1088:38)
at emitNone (events.js:86:13)
at TLSSocket.emit (events.js:188:7)
at TLSSocket._finishInit (_tls_wrap.js:610:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
Thu, 20 Apr 2017 09:29:01 GMT - info: Starting poll cycle with NODE_ENV Environment: default
Thu, 20 Apr 2017 09:29:01 GMT - info: getMonitorList for config: newrelic
Thu, 20 Apr 2017 09:29:01 GMT - error: Error on Insights monitor list call
Thu, 20 Apr 2017 09:29:01 GMT - error: Error: self signed certificate in certificate chain
at TLSSocket. (_tls_wrap.js:1088:38)
at emitNone (events.js:86:13)
at TLSSocket.emit (events.js:188:7)
at TLSSocket._finishInit (_tls_wrap.js:610:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)

**Comment by kenahrens** [comment]
@eshwarg - Do you use a proxy server to access the internet? If so can you set the environment variable `HTTPS_PROXY` with the URL to your proxy server?

**Comment by eshwarg** [comment]
New Relic Insights API Test
    1) calls the query api

  New Relic Plugin Make Metric Test
    ✓ makes a full metric name
    ✓ makes the complete metric JSON


  2 passing (902ms)
  1 failing

  1) New Relic Insights API Test calls the query api:
     Uncaught AssertionError: { Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
    at emitNone (event == null
      at quickAssert (test/test-insights.js:5:10)
      at Request._callback (test/test-insights.js:17:7)
      at self.callback (node_modules/request/request.js:188:22)
      at Request.onRequestError (node_modules/request/request.js:884:8)
      at TLSSocket.socketErrorListener (_http_client.js:358:9)
      at emitErrorNT (net.js:1283:8)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by eshwarg** [comment]
Yes , I am in office network but that should't be a problem.

**Comment by kenahrens** [comment]
I believe something in that network is blocking direct access to the API endpoint. If you use a proxy server with Chrome, Safari, etc. then you can tell this plugin about the proxy by setting the 'HTTPS_PROXY' environment variable. You can do that at the command line right before running the plugin.

Also if you could try from another network that would give us another data point as well.

**Comment by eshwarg** [comment]
bash-3.2$ set HTTP_PROXY=null
bash-3.2$ set HTTPS_PROXY=null
bash-3.2$ npm test

> nr-synthetics-plugin@2.0.4 test /Users/egoutham/Projects/nr-synthetics-plugin
> mocha



  New Relic Insights API Test
    1) calls the query api

  New Relic Plugin Make Metric Test
    ✓ makes a full metric name
    ✓ makes the complete metric JSON


  2 passing (910ms)
  1 failing

  1) New Relic Insights API Test calls the query api:
     Uncaught AssertionError: { Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
    at emitNone (event == null
      at quickAssert (test/test-insights.js:5:10)
      at Request._callback (test/test-insights.js:17:7)
      at self.callback (node_modules/request/request.js:188:22)
      at Request.onRequestError (node_modules/request/request.js:884:8)
      at TLSSocket.socketErrorListener (_http_client.js:358:9)
      at emitErrorNT (net.js:1283:8)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)



npm ERR! Test failed.  See above for more details.
bash-3.2$

**Comment by kenahrens** [comment]
Can you run a curl command like this so we can see what certificate you are getting? You need to replace YOUR_KEY_HERE with your Insights API Key and YOUR_ACCOUNT_ID with your account id. This is a modified version of the curl command from the API keys page in New Relic.

```
curl -vvI -H "Accept: application/json" -H "X-Query-Key: YOUR_KEY_HERE" "https://insights-api.newrelic.com/v1/accounts/YOUR_ACCOUNT_ID/query?nrql=SELECT%20average%28duration%29%20FROM%20PageView"
```

Here is part of the output I'm seeing:
```
* Connected to insights-api.newrelic.com (50.31.164.196) port 443 (#0)
* TLS 1.2 connection using TLS_RSA_WITH_AES_256_CBC_SHA256
* Server certificate: *.newrelic.com
* Server certificate: GeoTrust SSL CA - G3
* Server certificate: GeoTrust Global CA
```

**Comment by eshwarg** [comment]
I am not seeing the CA cert in my curl result... 

*   Trying xx.xx.xxx.xxx...
* Connected to insights-api.newrelic.com (xx.xx.xxx.xxx) port 443 (#0)
* TLS 1.2 connection using TLS_RSA_WITH_AES_256_CBC_SHA256
* Server certificate: *.newrelic.com
* Server certificate: xxxxx.xxxx.xxxx
> HEAD /v1/accounts/111111111/query?nrql=SELECT%20uniques%2
> Host: insights-api.newrelic.com

**Comment by eshwarg** [comment]
I am not seeing the CA cert in my curl result...

Trying xx.xx.xxx.xxx...
* Connected to insights-api.newrelic.com (xx.xx.xxx.xxx) port 443 (#0)
* TLS 1.2 connection using TLS_RSA_WITH_AES_256_CBC_SHA256
* Server certificate: *.newrelic.com
* Server certificate: xxxxx.xxxx.xxxx
* HEAD /v1/accounts/111111111/query?nrql=SELECT%20uniques%2
* Host: insights-api.newrelic.com

**Comment by kenahrens** [comment]
@eshwarg - That's good news that curl is able to see the proper SSL certificate. But that still doesn't explain why node sees a self-signed certificate. Something in your environment is attempting a man-in-the-middle attack on the API calls. Are you able to test from a different network or with a different computer? I've seen other users just spinning up a very small cloud instance to run this plugin. It does not need to run behind a firewall.

As another test you can try to turn on debug logging for tls. This didn't produce any interesting information on my machine. Set the environment variable NODE_DEBUG to the value tls, and run the test again. From my Mac:

```
kahrens:nr-synthetics-plugin kahrens$ export NODE_DEBUG=tls
kahrens:nr-synthetics-plugin kahrens$ npm test

> nr-synthetics-plugin@2.0.4 test /Users/kahrens/Documents/github/nr-synthetics-plugin
> mocha



  New Relic Insights API Test
TLS 53810: start
TLS 53810: secure established
    ✓ calls the query api (352ms)

  New Relic Plugin Make Metric Test
    ✓ makes a full metric name
    ✓ makes the complete metric JSON


  3 passing (360ms)
```

**Comment by eshwarg** [comment]
bash-3.2$ pwd
/Users/egoutham/Projects/nr-synthetics-plugin
bash-3.2$ export NODE_DEBUG=tls
bash-3.2$ npm test

> nr-synthetics-plugin@2.0.4 test /Users/egoutham/Projects/nr-synthetics-plugin
> mocha



  New Relic Insights API Test
TLS 45246: start
TLS 45246: secure established
    1) calls the query api

  New Relic Plugin Make Metric Test
    ✓ makes a full metric name
    ✓ makes the complete metric JSON


  2 passing (1s)
  1 failing

  1) New Relic Insights API Test calls the query api:
     Uncaught AssertionError: { Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
    at emitNone (event == null
      at quickAssert (test/test-insights.js:5:10)
      at Request._callback (test/test-insights.js:17:7)
      at self.callback (node_modules/request/request.js:188:22)
      at Request.onRequestError (node_modules/request/request.js:884:8)
      at TLSSocket.socketErrorListener (_http_client.js:358:9)
      at emitErrorNT (net.js:1283:8)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)



npm ERR! Test failed.  See above for more details.
bash-3.2$

**Comment by eshwarg** [comment]
Do we have any solution for this ? Could you check it once again from your end.

**Comment by kenahrens** [comment]
@eshwarg - Can you confirm the OS you are running, version of NodeJS and npm? I am going to try to test on a similar setup.

In the meantime do you have access to another machine to run this? It can literally run from anywhere since the New Relic APIs are publicly accessible. You can run in a Linux cloud instance fairly easily and inexpensively.

**Comment by kenahrens** [comment]
@eshwarg - I wanted to follow up on this. Can you try the curl command again and then print out the return code?

```
kahrens:nr-synthetics-plugin kahrens$ curl BLAHBLAH
...
* Connection #0 to host insights-api.newrelic.com left intact
kahrens:nr-synthetics-plugin kahrens$ echo $?
0
```

I'm interested to know what curl returns to the OS. If it is not 0 then your machine may have not be setup to trust our CA.
